### ISSUE TITLE
readGpioPinDigital return wrong value.

### ISSUE THREAD

**Issue by ghost** [igormiktor/AVRTools#1]
According to the documentation this macro should return 1 or 0 in fact it returns the bit value. That is; for  readGpioPinDigital(pPin00) it will return 0 or 1 but for readGpioPinDigital(pPin02) it will return 0 or 4 etc. 

So either the docs are wrong or the macro is wrong.

Otherwise though a nice set of tools.

**Comment by igormiktor** [comment]
Good catch.  The docs are wrong. In traditional C fashion, it returns 0 for "false" or a non-zero value for "true".

As you point out, the value returned is the bit value as determine by the bit position within the register.

I'll fix the documentation. 

Thanks.

**Comment by igormiktor** [comment]
Documentation corrected and updated.  Thanks again for pointing this out.
